#!/tmp/ruby-3.3.3-x86_64/inst/bin/ruby
# frozen_string_literal: true

#--
# Copyright 2006 by Chad Fowler, Rich Kilmer, Jim Weirich and others.
# All rights reserved.
# See LICENSE.txt for permissions.
#++

require "rubygems/gem_runner"

Gem::GemRunner.new.run ARGV.clone
