# This workflow exists so we do not have to locally generate the OpenAPI spec.
# If the OpenAPI spec has changed, it commits and pushes those changes back to the PR branch.

name: Generate and Commit OpenAPI Spec

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

# if this branch is pushed back to back, cancel the older branch's workflow
concurrency:
  group: ${{ github.ref }} && ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  generate-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read Node version from .nvmrc
        id: node_version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Generate OpenAPI docs from code
        run: |
          npm install -D tsx
          npm run generate:openapi

      - name: Commit OpenAPI changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add src/api-docs/openapi.json
					git add src/api-docs/openapi.yml
          git commit -m "Update OpenAPI spec"
          git push origin ${{ github.head_ref }}
        if: success()
