name: Run contract tests

on: push

concurrency:
  group: ${{ github.ref }} && ${{ github.workflow }}
  cancel-in-progress: true

env:
  PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_BRANCH: ${{ github.ref_name }}
  DATABASE_URL: 'file:./dev.db'
  PORT: 3001

jobs:
  contract-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read Node version from .nvmrc
        id: node_version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Set EXCLUDE_MAIN_AND_DEPLOYED based on PR description or commit messages
        uses: actions/github-script@v6
        with:
          script: |
            const prBody = context.payload.pull_request ? context.payload.pull_request.body || '' : '';
            let excludeFlag = false;

            if (prBody.includes('[pact-breaking-change]')) {
              excludeFlag = true;
              console.log('EXCLUDE_MAIN_AND_DEPLOYED set to true based on PR description.');
            } else {
              // Fetch commit messages
              const { data: commits } = await github.repos.listCommits({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: context.payload.pull_request.head.sha,
              });

              for (const commit of commits) {
                if (commit.commit.message.includes('[pact-breaking-change]')) {
                  excludeFlag = true;
                  console.log('EXCLUDE_MAIN_AND_DEPLOYED set to true based on commit message.');
                  break;
                }
              }
            }

            if (excludeFlag) {
              core.exportVariable('EXCLUDE_MAIN_AND_DEPLOYED', 'true');
            } else {
              console.log('EXCLUDE_MAIN_AND_DEPLOYED remains false.');
            }

      - name: Run provider contract tests
        run: npm run test:provider-ci

      - name: Can I deploy provider?
        run: npm run can:i:deploy:provider

      - name: Record provider deployment
        if: github.ref == 'refs/heads/main'
        run: npm run record:provider:deployment
