# This workflow exists so we do not have to locally generate the OpenAPI spec.
# If the OpenAPI spec has changed, it commits and pushes those changes back to the PR branch.

name: Generate & Commit OpenAPI

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: write
  actions: write

# if this branch is pushed back to back, cancel the older branch's workflow
concurrency:
  group: ${{ github.ref }} && ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  generate-commit-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }} # Ensure you're on the correct branch

      - name: Read Node version from .nvmrc
        id: node_version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Generate OpenAPI docs from code
        run: npm run generate:openapi

      - name: Check if OpenAPI docs have changed
        id: check_changes
        run: |
          if git diff --quiet src/api-docs/openapi.yml src/api-docs/openapi.json; then
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "changes=true" >> $GITHUB_ENV
          fi

      - name: Commit and push OpenAPI changes
        if: env.changes == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Update OpenAPI spec'
          add: 'src/api-docs/openapi.yml src/api-docs/openapi.json'
          push: true

      - name: Create empty commit to re-run checks
        if: env.changes == 'true'
        run: |
          git commit --allow-empty -m "Re-run checks after OpenAPI update"
          git push
