name: Run contract tests

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

concurrency:
  group: ${{ github.ref }} && ${{ github.workflow }}
  cancel-in-progress: true

env:
  PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_BRANCH: ${{ github.ref_name }}
  DATABASE_URL: 'file:./dev.db'
  PORT: 3001

jobs:
  contract-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read Node version from .nvmrc
        id: node_version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set EXCLUDE_MAIN_AND_DEPLOYED based on associated PR labels
        uses: actions/github-script@v6
        with:
          script: |
            const pr = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: context.payload.ref
            });

            if (pr.data.length > 0) {
              const labels = pr.data[0].labels.map(label => label.name);
              if (labels.includes('pact-breaking-change')) {
                core.exportVariable('EXCLUDE_MAIN_AND_DEPLOYED', 'true');
                console.log('EXCLUDE_MAIN_AND_DEPLOYED set to true based on PR label.');
              } else {
                console.log('EXCLUDE_MAIN_AND_DEPLOYED remains false.');
              }
            } else {
              console.log('No associated PR found.');
            }
            
      - name: Install dependencies
        run: npm ci

      - name: Run provider contract tests
        run: npm run test:provider-ci

      - name: Can I deploy provider?
        run: npm run can:i:deploy:provider

      - name: Record provider deployment
        if: github.ref == 'refs/heads/main'
        run: npm run record:provider:deployment
