name: Update README with Branch Name

on:
  pull_request:
    branches:
      - '**'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get the branch name
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF}" >> $GITHUB_ENV

      - name: Replace branch name in README
        run: |
          sed -i "s/{{BRANCH_NAME}}/${GITHUB_HEAD_REF}/g" PULL_REQUEST_TEMPLATE.md
