name: Run e2e tests
on:
  pull_request:
  workflow_dispatch:

# if this branch is pushed back to back, cancel the older branch's workflow
concurrency:
  group: ${{ github.ref }} && ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  DATABASE_URL: 'file:./dev.db'
  PORT: 3001
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Read Node version from .nvmrc
        id: node_version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Generate OpenAPI docs from code
        run: |
          npm install -D tsx
          npm run generate:openapi

      - name: Cypress e2e tests 🧪
        id: cypress-tests
        uses: cypress-io/github-action@v6.7.6
        with:
          start: npm run start
          config-file: cypress/config/local.config.ts
          record: true
          group: local
          tag: local

      # We do schema testing within the api e2e
      # We publish the OpenAPI spec on main, once after the PR is merged
      # Pact likes to have some file/evidence that the OpenAPI spec was tested
      # This section handles that need

      - name: Generate Verification Result for Success
        if: steps.cypress-tests.conclusion == 'success'
        run: echo "All Cypress tests passed." > cypress/verification-result.txt

      - name: Generate Verification Result for Failure
        if: steps.cypress-tests.conclusion != 'success'
        run: echo "Not all Cypress tests passed." > cypress/verification-result.txt

      - name: Commit and push verification result
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Update verification results'
          add: 'cypress/verification-result.txt'
          push: true
