name: Provider Contract Tests

on:
  repository_dispatch:
    types:
      - contract_requiring_verification_published

concurrency:
  group: ${{ github.ref }} && ${{ github.workflow }}
  cancel-in-progress: true

env:
  PACT_PAYLOAD_URL: ${{ github.event.client_payload.pact_url }}
  PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
  DATABASE_URL: 'file:./dev.db'
  PORT: 3001

jobs:
  verify_pact:
    runs-on: ubuntu-latest
    steps:
      - name: Log Payload Variables
        run: |
          echo "PACT_PAYLOAD_URL: ${{ env.PACT_PAYLOAD_URL }}"
          echo "GITHUB_SHA: ${{ github.event.client_payload.sha }}"
          echo "GITHUB_BRANCH: ${{ github.event.client_payload.branch }}"
          echo "PACT_BROKER_BASE_URL: ${{ env.PACT_BROKER_BASE_URL }}"
          echo "PACT_BROKER_TOKEN: [REDACTED]"

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Extract consumer branch name
        shell: bash
        env:
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
          PACT_PAYLOAD_URL: ${{ env.PACT_PAYLOAD_URL }}
        run: |
          echo "Fetching consumer branch from Pact Broker..."
          PACT_JSON=$(curl -s -H "Authorization: Bearer $PACT_BROKER_TOKEN" "$PACT_PAYLOAD_URL")
          echo "PACT_JSON: $PACT_JSON"
          CONSUMER_VERSION_URL=$(echo "$PACT_JSON" | jq -r '._links."pb:consumer-version".href')
          echo "CONSUMER_VERSION_URL: $CONSUMER_VERSION_URL"
          CONSUMER_VERSION_JSON=$(curl -s -H "Authorization: Bearer $PACT_BROKER_TOKEN" "$CONSUMER_VERSION_URL")
          echo "CONSUMER_VERSION_JSON: $CONSUMER_VERSION_JSON"
          CONSUMER_BRANCH=$(echo "$CONSUMER_VERSION_JSON" | jq -r '.branch')
          echo "Consumer branch extracted: $CONSUMER_BRANCH"
          echo "CONSUMER_BRANCH=$CONSUMER_BRANCH" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config --global init.defaultBranch main
          git init
          git remote add origin https://github.com/your-org/your-provider-repo.git

      - name: Checkout matching branch or default to main
        shell: bash
        run: |
          if git ls-remote --exit-code --heads origin "${CONSUMER_BRANCH}"; then
            echo "Branch '${CONSUMER_BRANCH}' exists in provider repository."
            echo "BRANCH_TO_CHECKOUT=${CONSUMER_BRANCH}" >> $GITHUB_ENV
          else
            echo "Branch '${CONSUMER_BRANCH}' does not exist in provider repository. Using 'main' branch."
            echo "BRANCH_TO_CHECKOUT=main" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_TO_CHECKOUT }}

      - name: Set GITHUB_BRANCH
        run: |
          CURRENT_BRANCH=$(git branch --show-current)
          echo "GITHUB_BRANCH=${CURRENT_BRANCH}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Run provider tests
        env:
          PACT_PAYLOAD_URL: ${{ env.PACT_PAYLOAD_URL }}
          PACT_BROKER_BASE_URL: ${{ env.PACT_BROKER_BASE_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
          GITHUB_SHA: ${{ github.event.client_payload.sha }}
          GITHUB_BRANCH: ${{ env.GITHUB_BRANCH }}
          DATABASE_URL: ${{ env.DATABASE_URL }}
          PORT: ${{ env.PORT }}
        run: npm run test:provider-ci

        # trigger
