# This workflow is triggered by a webhook when the consumer publishes a pact.
# It runs the provider's contract tests to verify the new pact.

name: Provider Contract Tests

on:
  repository_dispatch:
    types:
      - contract_requiring_verification_published

concurrency:
  group: ${{ github.ref }} && ${{ github.workflow }}
  cancel-in-progress: true

env:
  PACT_PAYLOAD_URL: ${{ github.event.client_payload.pact_url }}
  PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
  GITHUB_SHA: ${{ github.event.client_payload.sha }}
  DATABASE_URL: 'file:./dev.db'
  PORT: 3001

jobs:
  verify_pact:
    runs-on: ubuntu-latest
    steps:
      - name: Log Payload Variables
        run: |
          echo "PACT_PAYLOAD_URL: ${{ env.PACT_PAYLOAD_URL }}"
          echo "GITHUB_SHA: ${{ env.GITHUB_SHA }}"
          echo "GITHUB_BRANCH: ${{ github.event.client_payload.branch }}"

      - name: Extract consumer branch name
        shell: bash
        env:
          PACT_BROKER_TOKEN: ${{ env.PACT_BROKER_TOKEN }}
          PACT_PAYLOAD_URL: ${{ env.PACT_PAYLOAD_URL }}
        run: |
          echo "Fetching consumer branch from Pact Broker..."
          PACT_JSON=$(curl -s -H "Authorization: Bearer $PACT_BROKER_TOKEN" "$PACT_PAYLOAD_URL")
          echo "PACT_JSON: $PACT_JSON"
          CONSUMER_VERSION_URL=$(echo "$PACT_JSON" | jq -r '._links."pb:consumer-version".href')
          echo "CONSUMER_VERSION_URL: $CONSUMER_VERSION_URL"
          CONSUMER_VERSION_JSON=$(curl -s -H "Authorization: Bearer $PACT_BROKER_TOKEN" "$CONSUMER_VERSION_URL")
          echo "CONSUMER_VERSION_JSON: $CONSUMER_VERSION_JSON"
          CONSUMER_BRANCH=$(echo "$CONSUMER_VERSION_JSON" | jq -r '.branch')
          echo "Consumer branch extracted: $CONSUMER_BRANCH"
          echo "CONSUMER_BRANCH=$CONSUMER_BRANCH" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout matching branch or default to main
        shell: bash
        run: |
          git fetch origin ${{ env.CONSUMER_BRANCH }} || true
          if git rev-parse --verify origin/${{ env.CONSUMER_BRANCH }}; then
            git checkout ${{ env.CONSUMER_BRANCH }}
            echo "Checked out branch '${{ env.CONSUMER_BRANCH }}'"
          else
            git checkout main
            echo "Branch '${{ env.CONSUMER_BRANCH }}' does not exist. Defaulted to 'main'"
          fi
          CURRENT_BRANCH=$(git branch --show-current)
          echo "GITHUB_BRANCH=${CURRENT_BRANCH}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Run provider tests
        env:
          PACT_PAYLOAD_URL: ${{ env.PACT_PAYLOAD_URL }}
          PACT_BROKER_BASE_URL: ${{ env.PACT_BROKER_BASE_URL }}
          PACT_BROKER_TOKEN: ${{ env.PACT_BROKER_TOKEN }}
          GITHUB_SHA: ${{ env.GITHUB_SHA }}
          GITHUB_BRANCH: ${{ env.GITHUB_BRANCH }}
          DATABASE_URL: ${{ env.DATABASE_URL }}
          PORT: ${{ env.PORT }}
        run: npm run test:provider-ci
